name: CI

# 워크플로 트리거
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 소스 코드 체크아웃
      - uses: actions/checkout@v4

      - name: Trigger Jenkins CD
        if: success()
        env:
          JENKINS_URL: https://jenkins.overthecam.site
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JOB_NAME: overthecam-main
          JOB_TOKEN: ${{ secrets.JENKINS_JOB_TOKEN }}
        run: |
          # Crumb 받아오기
          CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          # Jenkins 빌드 트리거
          curl -v -X POST -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
            "$JENKINS_URL/job/$JOB_NAME/build?token=$JOB_TOKEN" \
            -H "$CRUMB"
